export const bgimage = './images/life-at-campus.jpg'
export const image1 = './images/IMG_9463.jpg'
export const image2 = './images/IMG_9439.jpg'
export const image3 = './images/IMG_9705.jpg'
export const image4 = './images/IMG_0348.jpg'
export const image5 = './images/IMG_0224.jpg'
export const image6 = './images/IMG_9706.jpg'
